project/cliente/urls.py
from django.urls import path

from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.home, name = "index"),
    path("crear/", views.crear, name="crearcliente"),
    path("eliminar/<int:id>", views.eliminarcliente, name="eliminar"),
    path("editar/<int:id>", views.editarcliente, name="editar"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
]

from django.conf.urls.static import static
from django.conf import settings

url_patterns_for_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + url_patterns_for_media

project/core/urls.py
from django.urls import path

from . import views


app_name = "core"

urlpatterns = [
    path("", views.home, name = "index"),
    path("about/", views.about, name = "about"),
    path("registro/", views.registro_view, name= "registro"),
    path("login/", views.login_view, name= "login"),
    path('logout/', views.view_logout, name='logout'),
    path("editar_perfil", views.editar_perfil_view, name="editar-perfil")
]

project/cliente/models.py
from django.db import models

class Cliente(models.Model):
   nombre = models.CharField(max_length=100) 
   apellido = models.CharField(max_length=100) 

   
   def __str__(self):
    return f"{self.nombre} {self.apellido}"

project/cliente/forms.py
from django import forms

from . import models

class ClienteForm(forms.ModelForm):
    class Meta:
        model= models.Cliente
        fields= ["nombre", "apellido"]

project/cliente/views.py
from django.shortcuts import render, redirect

from . import models

def home(request):
    clientes = models.Cliente.objects.all()
    context = {"clientes": clientes}

    return render(request, "cliente/index.html", context)

from . import forms

def crear(request):
    if request.method == "POST":
        form = forms.ClienteForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            cliente = models.Cliente(nombre=data["nombre"], apellido=data["apellido"])
            cliente.save()
            return redirect("cliente:index")
        return render(request, "cliente/crear.html", {"form": form})
    
    else:
        form = forms.ClienteForm()
        return render(request, "cliente/crear.html", {"form": form})
    
def eliminarcliente(request, id):
    
    if request.method == "POST":
        cliente = models.Cliente.objects.get(id=id)
        cliente.delete()
        clientes = models.Cliente.objects.all()
        return render(request, "cliente/index.html", {"clientes": clientes})

def editarcliente(request, id):
    cliente = models.Cliente.objects.get(id=id)

    if request.method == "POST":
        form = forms.ClienteForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            cliente.nombre = data["nombre"]
            cliente.apellido = data["apellido"]
            cliente.save()
            
            return redirect("cliente:index")
        return render(request, "cliente/editar.html", {"form": form})
    
    else:

        form = forms.ClienteForm(initial={
            "nombre": cliente.nombre,
            "apellido": cliente.apellido,
            })
        
        return render(request, "cliente/editar.html", {"form": form, "id": cliente.id})

project/cliente/templates/cliente/crear.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
 Agregar Cliente
{% endblock contenido_titulo %}

 
{% block contenido %}
        
<form action="{% url 'cliente:crearcliente' %}" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
</form>

{% endblock contenido %}
 

project/cliente/templates/cliente/editar.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
 Editar Cliente
{% endblock contenido_titulo %}

 
{% block contenido %}
        
<form action="{% url 'cliente:editar' id %}" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Editar">
</form>

{% endblock contenido %}

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
    Clientes
{% endblock contenido_titulo %}

{% block contenido %}
    <div class="container">
        <div class="row">
            {% for cliente in clientes %}
                <div class="col-md-6">
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">{{ cliente.apellido }}, {{ cliente.nombre }}</h5>
                            <p class="card-text">
                                <form action="{% url 'cliente:eliminar' cliente.id %}" method="POST"> {% csrf_token %}
                                    <button type="submit" class="btn btn-warning">Eliminar</button>
                                    <button class="btn btn-outline-primary">
                                        <a href="{% url 'cliente:editar' cliente.id %}" class="btn-link">
                                            <i class="fas fa-edit"></i> Editar
                                        </a>
                                    </button>
                                    
                                </form>
                       
                                

    
                                
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
            <a href="http://127.0.0.1:8000/cliente/crear" class="btn btn-primary">Agregar Cliente</a>
        </div>
    </div>
   </div>
{% endblock contenido %}




   