project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
]

from django.conf.urls.static import static
from django.conf import settings

url_patterns_for_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + url_patterns_for_media

project/core/urls.py
from django.urls import path

from . import views


app_name = "core"

urlpatterns = [
    path("", views.home, name = "index"),
    path("about/", views.about, name = "about"),
    path("registro/", views.registro_view, name= "registro"),
    path("login/", views.login_view, name= "login"),
    path('logout/', views.view_logout, name='logout'),
    path("editar_perfil", views.editar_perfil_view, name="editar-perfil")
]

project/producto/urls.py
from django.urls import path

from . import views

app_name = "producto"

urlpatterns = [
    path("", views.home, name="index"),
    path("crearproductos/", views.crearproductos,),
    path("busqueda/", views.busqueda),
    path("crear/", views.crear, name="creaproducto"),
    path("crearc/", views.crearc, name="creacategoria"),
    path("eliminar/<int:id>", views.eliminarproducto, name="eliminarp"),
    path("editar/<int:id>", views.editarproducto, name ="editar")
]

project/producto/models.py
from django.db import models

class Categoría(models.Model):
    nombre = models.CharField(max_length=100) 
 
    def __str__(self):
       return self.nombre  
 


class Producto(models.Model):
    nombre = models.CharField(max_length=100) 
    categoria = models.ForeignKey(Categoría, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
     return f"{self.nombre} {self.categoria}"


 

project/producto/forms.py
from django import forms

from . import models

class ProductoForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = ["nombre", "categoria"]


class CategoríaForm(forms.ModelForm):
    class Meta:
        model = models.Categoría
        fields = ["nombre"]

project/producto/views.py
from django.shortcuts import render, redirect

from . import models


def home(request):
    productos = models.Producto.objects.all()
    
    context1 = {"productos": productos}
 
    return render(request, "producto/index.html", context1)

#CREAR 
def crearproductos(request):
    c1 = models.Categoría(nombre="Limpieza")
    c1.save()
    p1 = models.Producto(nombre="Fabuloso", categoria=c1)
    p1.save()    
    return redirect("producto:index")

from . import forms

#Busqueda de productos
def busqueda(request):
     

     producto_nombre= models.Producto.objects.filter(nombre__contains="agua")
     context= {"producto_nombre":producto_nombre}
     return render(request, "producto/busqueda.html", context)


#Crear Productos
def crear(request):
    if request.method == "POST":
        form = forms.ProductoForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            producto = models.Producto(nombre=data["nombre"], categoria=data["categoria"])
            producto.save()
            return redirect("producto:index")
        return render(request, "producto/crear.html", {"form": form})
    
    else:
        form = forms.ProductoForm()
        return render(request, "producto/crear.html", {"form": form})

#Crear Categorias
def crearc(request):
    if request.method == "POST":
        form = forms.CategoríaForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            producto = models.Categoría(nombre=data["nombre"])
            producto.save()
            return redirect("producto:index")
        return render(request, "producto/crearc.html", {"form": form})
    
    else:
        form = forms.CategoríaForm()
        return render(request, "producto/crearc.html", {"form": form})
    

def eliminarproducto(request, id):
    
    if request.method == "POST":
        producto = models.Producto.objects.get(id=id)
        producto.delete()
        productos = models.Producto.objects.all()
        return render(request, "producto/index.html", {"productos": productos})

def editarproducto(request, id):
    producto = models.Producto.objects.get(id=id)

    if request.method == "POST":
        form = forms.ProductoForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            producto.nombre = data["nombre"]
            producto.categoria = data["categoria"]
            producto.save()
            
            return redirect("producto:index")
        return render(request, "producto/editar.html", {"form": form,})
    
    else:

        form = forms.ProductoForm(initial={
            "nombre": producto.nombre,
            "categoria": producto.categoria,
            })
        
        return render(request, "producto/editar.html", {"form": form, "id": producto.id})
    

project/producto/templates/producto/busqueda.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
    Búsqueda de Productos
{% endblock contenido_titulo %}

{% block contenido %}
    <div class="container">
        <div class="row">
            {% for producto in producto_nombre %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">{{ producto.nombre }}</h5>
                            <p class="card-text">{{ producto.categoria }}</p>
                            
                               
                            
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

  
{% endblock contenido %}

project/producto/templates/producto/crear.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
 Crear Producto
{% endblock contenido_titulo %}

 
{% block contenido %}
        
<form action="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Guardar</button>

</form>

{% endblock contenido %}
 

project/producto/templates/producto/crearc.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
 Crear nueva Categoría
{% endblock contenido_titulo %}

 
{% block contenido2 %}
        
<form action="{% url 'producto:creacategoria' %}" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar">
</form>

{% endblock contenido2 %}

project/producto/templates/producto/editar.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
 Editar Producto
{% endblock contenido_titulo %}

 
{% block contenido %}
        
<form action="{% url 'producto:editar' id %}" method="POST">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Editar">
</form>

{% endblock contenido %}
 

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
    Productos
{% endblock contenido_titulo %}

{% block contenido %}
    <div class="container">
        <div class="row">
            {% for producto in productos %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">{{ producto.nombre }}</h5>
                            <p class="card-text">{{ producto.categoria }}</p>
                            <form action="{% url 'producto:eliminarp' producto.id %}" method="POST"> {% csrf_token %}
                                <button type="submit" class="btn btn-warning">Eliminar</button>
                                <button class="btn btn-outline-primary">
                                    <a href="{% url 'producto:editar' producto.id %}" class="btn-link">
                                        <i class="fas fa-edit"></i> Editar
                                    </a>
                                </button>
                                
                            </form>


                            

                            
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row mt-4">
      <div class="col-md-12">
          <a href="http://127.0.0.1:8000/producto/crear/" class="btn btn-primary">Agregar Producto </a>
          <a href="http://127.0.0.1:8000/producto/crearc/" class="btn btn-primary">Agregar Categoría </a>
          <a href="http://127.0.0.1:8000/producto/busqueda/" class="btn btn-secondary">Búsqueda de Productos </a>
      </div>
  </div>
 </div>
 

   



{% endblock contenido %}