project/cliente/urls.py
from django.urls import path

from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.home, name = "index"),
    path("crear/", views.crear, name="crearcliente"),
    path("eliminar/<int:id>", views.eliminarcliente, name="eliminar"),
    path("editar/<int:id>", views.editarcliente, name="editar"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("producto/", include("producto.urls")),
]

from django.conf.urls.static import static
from django.conf import settings

url_patterns_for_media = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = urlpatterns + url_patterns_for_media

project/core/urls.py
from django.urls import path

from . import views


app_name = "core"

urlpatterns = [
    path("", views.home, name = "index"),
    path("about/", views.about, name = "about"),
    path("registro/", views.registro_view, name= "registro"),
    path("login/", views.login_view, name= "login"),
    path('logout/', views.view_logout, name='logout'),
    path("editar_perfil", views.editar_perfil_view, name="editar-perfil")
]

project/producto/urls.py
from django.urls import path

from . import views

app_name = "producto"

urlpatterns = [
    path("", views.home, name="index"),
    path("crearproductos/", views.crearproductos,),
    path("busqueda/", views.busqueda),
    path("crear/", views.crear, name="creaproducto"),
    path("crearc/", views.crearc, name="creacategoria"),
    path("eliminar/<int:id>", views.eliminarproducto, name="eliminarp"),
    path("editar/<int:id>", views.editarproducto, name ="editar")
]

project/core/models.py
from django.db import models
from django.contrib.auth.models import User


class Avatar(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.FileField(upload_to="media/avatares", null=True, blank=True)

    def __str__(self):
        return f"{self.user} {self.imagen}"

project/core/forms.py
#### REGISTRO
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, UserModel

class UserCreationFormulario(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
      model = UserModel
      fields = ["password1", "password2", "username", "email"]
      help_texts = {k: "" for k in fields}

class UserEditionFormulario(UserCreationForm):
   email = forms.EmailField()
   password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
   password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
   first_name = forms.CharField(label="Nombre")
   last_name = forms.CharField(label="Apellido")

   class Meta:
      model = UserModel
      fields = ["email", "password1", "password2", "first_name", "last_name"]
      help_texts = {k: "" for k in fields}
   

project/core/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required

#############################     CLASS BASED VIEWS (CBV)     ###########################
#from django.views.generic import ListView, CreateView, UpdateView, DetailView
#from django.urls import reverse_lazy
#from django.contrib.auth.mixins import LoginRequiredMixin
#########################################################################################

def home(request):
     
    
    return render(request, "core/index.html")

@login_required
def about(request):
    return render(request, "core/about.html")

def registro_view(request):

    if request.method == "GET":
        return render(request, "core/registro.html", {"form": forms.UserCreationFormulario()})

    else:
        formulario = forms.UserCreationFormulario(request.POST) 
        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = informacion["username"]
            formulario.save()

            return render(request, "core/index.html", {"mensaje": f"Usuario creado: {usuario}"})
        
        else:
            return render(request, "core/registro.html", {"form": formulario})
    
def login_view(request):

    if request.user.is_authenticated:
        return render(request, "core/index.html", {"mensaje": f"Ya estás autenticado en la web cómo: {request.user.username}"})
    
    if request.method == "GET":
        return render(request, "core/login.html", {"form": AuthenticationForm()})
    else:
        formulario = AuthenticationForm(request, data=request.POST)

        if formulario.is_valid():
            informacion = formulario.cleaned_data
            usuario = informacion["username"]
            password = informacion["password"]
            modelo = authenticate(username=usuario, password=password)
            login(request, modelo)
            return render(request, "core/index.html", {"mensaje": f"Bienvenido {modelo.username}"})
        else:
            return render(request, "core/login.html", {"form": formulario})

def view_logout(request):
    logout(request)
    return render(request,"core/logout.html")    

@login_required
def editar_perfil_view(request):

    usuario = request.user
    avatar = models.Avatar.objects.filter(user=usuario).first()
    avatar_url = avatar.imagen.url if avatar is not None else ""

    if request.method == "GET":
        
        valores_iniciales = {"email": usuario.email, "first_name": usuario.first_name, "last_name": usuario.last_name }
        
        
        formulario = forms.UserEditionFormulario(initial=valores_iniciales)
        return render(request, "core/editar-perfil.html", context={"form": formulario, "usuario": usuario, "avatar_url": avatar_url}) 
    
    else:
        formulario = forms.UserEditionFormulario(request.POST)
        if formulario.is_valid():
            informacion = formulario.cleaned_data

            usuario.email = informacion["email"]

            usuario.set_password(informacion["password1"])

            usuario.first_name = informacion["first_name"]
            usuario.last_name = informacion["last_name"]
            usuario.save()
        return redirect("core:index")
    

project/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
    <h1 class="display-4">Acerca de Smart Market</h1>
{% endblock contenido_titulo %}

{% block contenido %}
    <p>Bienvenido a Smart Market, una plataforma creada por Mathias Mallarini para la gestión eficiente y segura de diferentes tipos de información.</p>

    <p>Smart Market te ofrece un entorno digital versátil y fácil de usar que te permite archivar y organizar datos de manera efectiva. Ya sea que estés administrando información comercial, personal o creativa, Smart Market está diseñado para adaptarse a tus necesidades.</p>

    <p>Con una interfaz intuitiva, Smart Market simplifica el proceso de archivar y acceder a tu información, brindándote una experiencia fluida y eficiente.</p>

    <p>¡Explora Smart Market y descubre cómo esta plataforma puede facilitar la organización y gestión de tu información de manera inteligente!</p>
{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>SMarket</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        {% include 'core/navbar.html' %}


        <!-- Header--> 
       
            <div class="container px-4 px-lg-5 my-5">
                
                <h1>
                 {% block contenido_titulo %}
                 {% endblock contenido_titulo %}
                </h1>
                
                {% block contenido %} 
                {% endblock contenido %}

                {% block contenido2 %}
                {% endblock contenido2 %}


                
               
            </div>
        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; SMarket 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/card.html
{% load static %}

<div class="col mb-5">
    <div class="card h-100">
        <!-- Product image-->
        <img class="card-img-top" src="{% static 'core/img/productos.webp' %}" alt="..." />
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder">{{ title }}</h5>
                <!-- Product price-->
                {{ price }}
            </div>
        </div>
        <!-- Product actions-->
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="http://127.0.0.1:8000/producto/">Ver Productos</a></div>
        </div>
    </div>
</div>

project/core/templates/core/card2.html
{% load static %}

<div class="col mb-5">
    <div class="card h-100">
        <!-- Product image-->
        <img class="card-img-top" src="{% static 'core/img/cliente.webp' %}" alt="..." />
        <!-- Product details-->
        <div class="card-body p-4">
            <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder">{{ title }}</h5>
                <!-- Product price-->
                {{ price }}
            </div>
        </div>
        <!-- Product actions-->
        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="http://127.0.0.1:8000/cliente/">Ver Clientes</a></div>
        </div>
    </div>
</div>

project/core/templates/core/editar-perfil.html
{% extends 'core/base.html' %}

{% block contenido%}
<!DOCTYPE html>
 <html lang="en">

 <div>
    <h6>
        Editar usuario: {{ usuario }}
    </h6>

    <div >
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Guardar" >
        </form>
    </div>

</div>
{% endblock contenido %}

project/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}

{% endblock contenido_titulo %}

 
{% block contenido %}
{% if mensaje %}
    <div class="alert alert-warning mt-3" role="alert">
        {{ mensaje }}
    </div>
{% endif %}
<header class="bg-dark py-5">
   <div class="text-center text-white">
    <h1 class="display-4 fw-bolder">Archiva tú Información en la Web !</h1>
    <p class="lead fw-normal text-white-50 mb-0">Smart Market</p>
   </div>
</header>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        
        {% include 'core/card.html' with title="Productos" %} 
        {% include 'core/card2.html' with title="Clientes" %} 
         
                
            
        </div>
    </div>
</section>

{% endblock contenido %}

   
  

project/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block contenido %}

<h2>Login de Usuario</h2>
<body>
    <form action="" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Iniciar sesión">
    </form>
</body>

{% endblock contenido %}

project/core/templates/core/logout.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
{% endblock contenido_titulo %}

{% block contenido %}
<h2>Te has deslogeado</h2>
{% endblock contenido %}

project/core/templates/core/navbar.html
<!-- NavBar-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">Smart Market</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:about' %}">About</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Info</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'producto:index' %}">Productos</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{% url 'cliente:index' %}">Clientes</a></li>
                    </ul>
                </li>
            </ul>

            <!-- Aqui añado las clases a la derecha -->
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'core:editar-perfil' %}">Editar Perfil {{ user.username }}</a>
                    <img src="{{ avatar_url }}" alt="Avatar" style="height: 40px; width: 40px; border-radius: 50%; object-fit: cover; object-position: center; border: 2px solid #fff;"/>
                    <a class="btn btn-outline-danger nav-item nav-link" href="{% url 'core:logout' %}">Cerrar sesión</a>
                </div>
            {% else %}
                <div class="navbar-nav">
                    <a class="btn btn-outline-primary nav-item nav-link" href="{% url 'core:login' %}">Iniciar sesión</a>
                    <a class="btn btn-outline-success nav-item nav-link" href="{% url 'core:registro' %}">Registrarse</a>
                </div>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>

project/core/templates/core/registro.html
{% extends 'core/base.html' %}

{% block contenido %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <style>
        .error-list {
            color: red;
        }
    </style>
</head>

<body>
<h2>Registro de Usuario</h2>
<form action="" method="POST">
    {% csrf_token %}

    {% for field in form %}
        <p>
            {{ field.label_tag }}
            {{ field }}

            {% if field.errors %}
                <ul class="error-list">
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </p>
    {% endfor %}

    <input type="submit" value="Registrar Usuario">
</form>
</body>
</html>
{% endblock contenido %}